---
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/basic_go.yml@62d42ce3380edb748e7e37fce695bf1e10bf466a
    with:
      coverage-excludes-regex: "/.*test.*"
      tests-excludes-regex: "/.*test.*"
      skip-race-tests: true

  linter:
    uses: openconfig/common-ci/.github/workflows/linter.yml@62d42ce3380edb748e7e37fce695bf1e10bf466a
