name: Go

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  common:
    uses: openconfig/common-ci/.github/workflows/go.yml@6a79488e4abedcddca75fda8fb19ee61b7bc7be2
