---
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  common:
    uses: openconfig/common-ci/.github/workflows/go.yml@469e3a5e2cba6d06571d43e9a42f5d9138db9af4
    with:
      coverage-excludes-regex: "/.*test.*"
      tests-excludes-regex: "/.*test.*"
      race-tests-excludes-regex: "/.*test.*"
